//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3031
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankOfPluto.localhost {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="localhost.IManagerServices")]
    public interface IManagerServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagerServices/GetPersonByTaxId", ReplyAction="http://tempuri.org/IManagerServices/GetPersonByTaxIdResponse")]
        BoP.Core.Domain.Person GetPersonByTaxId(string taxId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagerServices/UpdatePerson", ReplyAction="http://tempuri.org/IManagerServices/UpdatePersonResponse")]
        BoP.Core.Domain.Person UpdatePerson(BoP.Core.Domain.Person newP, BoP.Core.Domain.Person oldP);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IManagerServicesChannel : BankOfPluto.localhost.IManagerServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ManagerServicesClient : System.ServiceModel.ClientBase<BankOfPluto.localhost.IManagerServices>, BankOfPluto.localhost.IManagerServices {
        
        public ManagerServicesClient() {
        }
        
        public ManagerServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ManagerServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ManagerServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ManagerServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BoP.Core.Domain.Person GetPersonByTaxId(string taxId) {
            return base.Channel.GetPersonByTaxId(taxId);
        }
        
        public BoP.Core.Domain.Person UpdatePerson(BoP.Core.Domain.Person newP, BoP.Core.Domain.Person oldP) {
            return base.Channel.UpdatePerson(newP, oldP);
        }
    }
}
